apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aggregator-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - name: aggregator-service
        image: eu.gcr.io/deploy-software-on-kubernetes/aggregator-service:3.0	
        ports:
        - containerPort: 8081
