apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aggregator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - name: aggregator-service
<<<<<<< HEAD
        image: eu.gcr.io/deploying-software-on-kubernetes/aggregator-service:2.0
=======
        image: eu.gcr.io/deploy-software-on-kubernetes/aggregator-service:1.0
>>>>>>> f5aa9114ab22a2dd48561ca7dbc2fbe8b9ad3965
        ports:
        - containerPort: 8080
